- lib/valid_email/validate_email.rb
- spec/validate_email_spec.rb
Many mail servers do not accept emails to addresses like <foo.bar.@gmail.com>, so we should treat them as invalid.
See http://www.remote.org/jochen/mail/info/chars.html for details.
> Do not allow double dots and dots in beginning or end of local part of address

- lib/valid_email/validate_email.rb
- spec/validate_email_spec.rb
Manually handling exceptions caused by invalid local segments of email addresses is always a hassle, o I figured it made sense to extend this library to cover the full gamut of requirements outlined in [RFC-5322](http://tools.ietf.org/html/rfc5322), specifically sections 3.2.3 and 3.2.4. I specifically eschewed using any regular expressions per this library's documentation.
For a more accessible guide to the rules I'm matching check out [this discussion](https://social.technet.microsoft.com/Forums/exchange/en-US/69f393aa-d555-4f8f-bb16-c636a129fc25/what-are-valid-and-invalid-email-address-characters).
Thanks for your consideration! Let me know if there's anything you think should be tweaked!
> Added local segment validation to email validator

- valid_email.gemspec
I picked the MIT license, as the LICENSE file looks like MIT.
I would like to add this because it will make automated license checking using [dblock/gem-license](https://github.com/dblock/gem-licenses) easier.
> Add license flag to the gemspec

- lib/valid_email/ban_disposable_email_validator.rb
- lib/valid_email/email_validator.rb
- lib/valid_email/mx_validator.rb
- lib/valid_email/validate_email.rb
This file needed a ```require 'mail'``` to eliminate the exception.
> fix uninitialized constant in lib/valid_email/validate_email.rb

- lib/valid_email/email_validator.rb
Like all other rails validators, error message translations may now contain %{value}, which is interpolated with the invalid email.
> Support interpolation of validation error messages

- lib/valid_email/validate_email.rb
This enables the use of `ValidateEmail` in pure Ruby projects that don't
patch `String#present?`
Fixes #64
> Replace #present? usage to !#empty?

- lib/valid_email/email_validator.rb
- spec/email_validator_spec.rb
Supplying a message does not currently work if you also use one of the other options, such as mx, ban_disposable_email, etc, because message is not passed to the secondary validators.
> Fix message option

- lib/valid_email/validate_email.rb
If MX-record exists, avoid doing redundant A-record check
> Avoid redundant A-record lookup

- lib/valid_email/validate_email.rb
- spec/validate_email_spec.rb
Hello,
this pull requests allows umlauts domains. 
I have added a test case for German umlauts, and moved your Russian invalid example to a valid example (the Russian domain from the test is even registered).
While it is possible that some NICs might in the future block non-ASCII characters from their TLDs, currently everyone allows it.
If removing these characters was a design decision, please let me know.
> Allow non-ascii alphabetical characters in domain

- .travis.yml
CI failing due to the release of bundler 2.0.
> Use bundler 1.17.3 to pass CI in Ruby < 2.3

- lib/valid_email/validate_email.rb
- spec/validate_email_spec.rb
`ValidateEmail#domain_valid?` (which is also called from `ValidateEmail#valid?` by default) fails to handle real email addresses like `@is.s.u-tokyo.ac.jp` (mine). Together with the bug, I've improved the regex in several ways.
- The regex contained duplicate start-of-string designators `/\A^/`. I've removed the latter.
- I've replaced `()` with non-capturing ones `(?:)`.
- Single-letter segments (labels) were erroneously rejected if placed after the first segment. Fixed.
- Single-digit segments were erroneously rejected. Note that the labels like `0clickemail` have already been accepted by the regex. Labels starting with digits were disallowed in RFC0952/RFC1035 but later allowed in RFC1123.
- Not all international domain names were allowed. I've fixed this to uniformly allow …
>  Fix bugs in DOMAIN_REGEX

- valid_email.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement. This PR removes that property.
* [RubyForge was closed down in 2013][1].
* [rubygems/rubygems#2436 deprecated the `rubyforge_project` property][2].
[1]: https://twitter.com/evanphx/status/399552820380053505
[2]: rubygems/rubygems#2436
> gemspec: Drop defunct property rubyforge_project

- spec/validate_email_spec.rb
Mock MX DNS query to return nothing
Now it returns
; <<>> DiG 9.10.6 <<>> mx example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29253
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;example.com.			IN	MX
;; ANSWER SECTION:
example.com.		86085	IN	MX	0 .
;; Query time: 359 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Mon Apr 13 16:11:11 EAT 2020
;; MSG SIZE  rcvd: 55
> [spec] Mock MX resolution of example.org to nothing

- lib/valid_email/validate_email.rb
- spec/validate_email_spec.rb
- valid_email.gemspec
Attempting to MX-validate email addresses with non-ASCII domain names results in encoding errors from `Resolv::DNS`. This PR IDNA-encodes such domains before trying to resolve them.
DNS supports only ASCII characters; however, many applications support non-ASCII characters in domain names, and use [IDNA](https://tools.ietf.org/html/rfc3490) to encode these as ASCII when making DNS requests. This includes mailservers, with IDNA now incorporated into [SMTP standards](https://tools.ietf.org/html/rfc6531), and IDN mailboxes increasingly being supported in popular MTAs.
`valid_email` uses the `mail` gem to extract the domain name from an email address, but because this gem isn't concerned with DNS, it doesn't need to handle IDNA-encoding. Meanwhile, the ruby stdlib `Resolv::DNS` [doesn't …
> IDNA-encode domain names with non-ASCII chars before MX lookup

- .travis.yml
Ruby 3.0 was released on 25 Dec 2020. It's a good time to testing and using the gem on this platform as well.
> Test Ruby 3.0 support using Travis CI

- README.md
Reformat the `README.md` file with Markdown. The README file took some cleanup. The code was not colored correctly, there was no consistency. I focused on the visual aspect, because the README file is the only documentation of this gem.
> Update README using markdown format

- config/valid_email.yml
qq.com is not really a disposable emails, it is tied to user's phone numbers: https://www.serviceobjects.com/blog/the-trouble-with-numeric-and-fake-looking-chinese-email-addresses/
> Remove qq.com from blacklist

- spec/email_validator_spec.rb
These anonymous classes in tests contain common code. I decided to move this common code to a separate class and take advantage of inheritance for anonymous classes.
But we don't want to define a class in the body of a method. Therefore, as the base class from which we inherit,  we use also anonymous class.
> Refactoring anonymous classes in tests

- lib/valid_email/validate_email.rb
Negating the conditions reduces readability.
Therefore, instead of negating `any?` method called on a collection, is it better to call `none?` method on this collection.
> Change !any? to none?

- lib/valid_email/email_validator.rb
- spec/email_validator_spec.rb
Currently, the error message is passed as a type for an `ActiveModel::Error` instance.
```Ruby
record.errors.add attribute, (msg % {value: value})
```
The problem is that if there is any specific behavior based on the error type exists, it's barely possible to identify the error, especially with multiple locales used
```Ruby
if instance.errors.details[:email].include?(:invalid) 
end
instance.errors.details #=> { :email=>[{ :error=><a particular locale message> }] }
```
For example,
```Ruby
class MyClass
include ActiveModel::Validations
attr_accessor :email
validates :email, email: true
end
instance = MyClass.new
instance.valid?
```
Errors:
```Ruby
instance.errors #=> [#<ActiveModel::Error attribute=email, type=<a particular locale message>, options={}>]>
```
So if we need to know whether …
> Pass error message as a message option instead of the type

- .rspec
- .travis.yml
- lib/valid_email/email_validator.rb
This gem is creating `email_validator.rb:25: warning: too many arguments for format string` warnings, which are harmless, but cost mental overhead every time I run the specs.
SInce I18n is already used and the format feels almost expected to go through it, I replaced the call with I18n.interpolate, which has existed with the same api since 2010.
Current specs suffice. 
I also add `--warning` to `.rspec`, to make the warnings visible during development. There are still some warnings printed from the email gem, but they are working on that (https://github.com/mikel/mail/pull/1551).
And I added ruby 3.1 and 3.2 to the travis matrix.
Please let me know what you think and if I should change anything.
> Remove 'too many arguments for format string' warning
